feat : variants implementation
contentstack/contentstack-java pull request #121
Opened 2024-06-25 07:30 UTC by reeshika-h

- Variants implementation
- Unit and API Testcases

2024-06-25 13:30 UTC, nadeem-cs requested changes

2024-06-25 13:30 UTC, nadeem-cs commented on src/main/java/com/contentstack/sdk/Entry.java
> +   if (variants != null && variants.length() > 0) {
@reeshika-h Please improve the indentation. This increases code-readability.

2024-06-27 07:21 UTC, reeshika-h commented on src/main/java/com/contentstack/sdk/Entry.java
> +   if (variants != null && variants.length() > 0) {
ok

2024-06-27 07:21 UTC, reeshika-h commented on src/test/java/com/contentstack/sdk/TestEntry.java
> +        entry = stack.contentType(CONTENT_TYPE).entry(entryUid).variants("  cs672c33271558d8b0 ");
ok

2024-06-27 07:48 UTC, closed without merging